// Command gen-gitleaks-rules turns the gitleaks default ruleset into an
// OpenTelemetry Collector `transform` processor config that redacts secrets
// out of ingested telemetry before it is written to ClickHouse.
//
// It is an OFFLINE generator, run by hand — not part of the build. Its output,
// collector/redaction.yaml, is committed so reviewers see the expanded regex
// set in the diff and CI never has to depend on the gitleaks module. To
// refresh the rules after a gitleaks release:
//
//	# update the pinned version in collector/gitleaks.toml, then:
//	cd collector/gen-gitleaks-rules
//	go run . -in ../gitleaks.toml -out ../redaction.yaml
//	# review and commit the redaction.yaml diff
//
// Why the write path stays codeless: rather than a custom Collector component
// linking gitleaks' Go API (which would force a bespoke otelcol build and
// contradict the "stock components only" rule the README states), we lift the
// regexes out of gitleaks' rule pack and emit stock `transform`/OTTL
// statements. The expansion is mechanical; the collector that runs it is
// unmodified upstream.
//
// Mapping, per gitleaks rule with a usable regex:
//
//	replace_pattern(body, "<regex>", "REDACTED:<ruleID>")               # log bodies
//	replace_all_patterns(attributes, "value", "<regex>", "REDACTED:<ruleID>")  # log & span attrs
//
// gitleaks allowlists are deliberately NOT translated: they exist to cut
// false positives while *scanning a repo*, and have no clean streaming
// equivalent here — a matched value is redacted regardless. Over-redaction is
// safe; leaking a secret is not.
//
// Rules whose regex does not compile under Go's stock regexp/RE2 engine (the
// same engine OTTL's replace_pattern uses) are skipped and reported, so every
// statement emitted is guaranteed to load in the collector.
package main

import (
	"flag"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"

	"github.com/pelletier/go-toml/v2"
)

// gitleaksVersion is the gitleaks release collector/gitleaks.toml was taken
// from. Bump it in lockstep when you refresh the toml, so the generated
// header records exactly which rule pack produced redaction.yaml.
const gitleaksVersion = "v8.30.1"

// gitleaksConfig is the subset of gitleaks' TOML schema we consume: each rule
// contributes an id and a regex; everything else (descriptions, keywords,
// entropy, allowlists) is irrelevant to substring redaction.
type gitleaksConfig struct {
	Rules []struct {
		ID    string `toml:"id"`
		Regex string `toml:"regex"`
	} `toml:"rules"`
}

func main() {
	in := flag.String("in", "../gitleaks.toml", "path to the gitleaks default ruleset (TOML)")
	out := flag.String("out", "../redaction.yaml", "path to write the generated transform-processor config")
	flag.Parse()

	raw, err := os.ReadFile(*in)
	if err != nil {
		fail("read %s: %v", *in, err)
	}

	var cfg gitleaksConfig
	if err := toml.Unmarshal(raw, &cfg); err != nil {
		fail("parse %s: %v", *in, err)
	}

	rules, skipped := usableRules(cfg)
	if len(rules) == 0 {
		fail("no usable rules found in %s", *in)
	}

	yaml := render(rules, skipped)
	if err := os.WriteFile(*out, []byte(yaml), 0o644); err != nil {
		fail("write %s: %v", *out, err)
	}

	fmt.Fprintf(os.Stderr, "wrote %s: %d rules, %d skipped (uncompilable regex)\n",
		*out, len(rules), len(skipped))
}

type rule struct {
	id    string
	regex string
}

// usableRules keeps rules with a non-empty regex that compiles under Go's
// stock regexp engine — the same RE2 engine OTTL's replace_pattern compiles
// with — so nothing we emit can fail to load in the collector. Rules are
// returned sorted by id for a stable diff, deduplicated by id.
func usableRules(cfg gitleaksConfig) (keep []rule, skipped []string) {
	seen := make(map[string]bool)
	for _, r := range cfg.Rules {
		if r.ID == "" || r.Regex == "" || seen[r.ID] {
			continue
		}
		seen[r.ID] = true
		if _, err := regexp.Compile(r.Regex); err != nil {
			skipped = append(skipped, r.ID)
			continue
		}
		keep = append(keep, rule{id: r.ID, regex: r.Regex})
	}
	sort.Slice(keep, func(i, j int) bool { return keep[i].id < keep[j].id })
	sort.Strings(skipped)
	return keep, skipped
}

func render(rules []rule, skipped []string) string {
	var b strings.Builder
	b.WriteString("# GENERATED by collector/gen-gitleaks-rules — DO NOT EDIT BY HAND.\n")
	b.WriteString("#\n")
	fmt.Fprintf(&b, "# Source ruleset: gitleaks %s (collector/gitleaks.toml).\n", gitleaksVersion)
	fmt.Fprintf(&b, "# %d rules expanded; %d skipped (regex not RE2-compilable).\n", len(rules), len(skipped))
	if len(skipped) > 0 {
		fmt.Fprintf(&b, "# Skipped: %s\n", strings.Join(skipped, ", "))
	}
	b.WriteString("#\n")
	b.WriteString("# This is the body of a stock `transform` processor. The harness config\n")
	b.WriteString("# (ci/otel-collector-config.yaml) loads it with\n")
	b.WriteString("#   transform/redaction: ${file:/etc/otelcol/redaction.yaml}\n")
	b.WriteString("# and runs it ahead of `batch` in the logs and traces pipelines. Each rule\n")
	b.WriteString("# replaces any matching substring in a log body or a log/span attribute\n")
	b.WriteString("# value with REDACTED:<ruleID>, so secrets never reach ClickHouse.\n")
	b.WriteString("#\n")
	b.WriteString("# Regenerate with: cd collector/gen-gitleaks-rules && go run .\n")
	b.WriteString("\n")

	b.WriteString("error_mode: ignore\n")
	b.WriteString("\n")

	b.WriteString("log_statements:\n")
	b.WriteString("  - context: log\n")
	b.WriteString("    statements:\n")
	for _, r := range rules {
		b.WriteString(stmtLine(fmt.Sprintf(
			`replace_pattern(body, "%s", "REDACTED:%s")`, ottlEscape(r.regex), r.id)))
		b.WriteString(stmtLine(fmt.Sprintf(
			`replace_all_patterns(attributes, "value", "%s", "REDACTED:%s")`, ottlEscape(r.regex), r.id)))
	}
	b.WriteString("\n")

	b.WriteString("trace_statements:\n")
	b.WriteString("  - context: span\n")
	b.WriteString("    statements:\n")
	for _, r := range rules {
		b.WriteString(stmtLine(fmt.Sprintf(
			`replace_all_patterns(attributes, "value", "%s", "REDACTED:%s")`, ottlEscape(r.regex), r.id)))
	}

	return b.String()
}

// stmtLine renders one OTTL statement as a YAML single-quoted list item.
// Single-quoted YAML passes backslashes and double quotes through verbatim
// (only a literal single quote needs doubling), which keeps the two escaping
// layers independent: YAML leaves the string alone, and OTTL then unquotes the
// inner "..." itself.
func stmtLine(stmt string) string {
	return "      - '" + strings.ReplaceAll(stmt, "'", "''") + "'\n"
}

// ottlEscape prepares a Go/RE2 regex for embedding inside an OTTL
// double-quoted string literal that the collector loads through confmap.
// Three layers each want their own escape:
//
//   - OTTL unquotes string literals (so `\\d` becomes the regex `\d`, matching
//     the transformprocessor docs' own examples), hence every backslash is
//     doubled and every double quote escaped.
//   - confmap runs `${...}`/`$VAR` expansion over every resolved string value,
//     including the ones this file supplies, and uses `$$` for a literal `$`.
//     A gitleaks regex is full of `$` anchors, so each is doubled to survive
//     expansion as a plain `$`.
//
// (The YAML layer is handled by stmtLine, which single-quotes the statement so
// backslashes and double quotes pass through untouched.)
func ottlEscape(re string) string {
	re = strings.ReplaceAll(re, `\`, `\\`)
	re = strings.ReplaceAll(re, `"`, `\"`)
	re = strings.ReplaceAll(re, `$`, `$$`)
	return re
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen-gitleaks-rules: "+format+"\n", args...)
	os.Exit(1)
}
